/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.automatski.autosim.ureactive.api;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TupleCollection implements org.apache.thrift.TBase<TupleCollection, TupleCollection._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TupleCollection");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField CORRELATION_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("correlationId", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField CATEGORY_GUIDS_FIELD_DESC = new org.apache.thrift.protocol.TField("categoryGuids", org.apache.thrift.protocol.TType.LIST, (short)3);
  private static final org.apache.thrift.protocol.TField HEADERS_FIELD_DESC = new org.apache.thrift.protocol.TField("headers", org.apache.thrift.protocol.TType.MAP, (short)4);
  private static final org.apache.thrift.protocol.TField TUPLES_FIELD_DESC = new org.apache.thrift.protocol.TField("tuples", org.apache.thrift.protocol.TType.LIST, (short)5);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TupleCollectionStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TupleCollectionTupleSchemeFactory());
  }

  public String id; // required
  public String correlationId; // required
  public List<String> categoryGuids; // required
  public Map<String,String> headers; // required
  public List<Tuple> tuples; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    CORRELATION_ID((short)2, "correlationId"),
    CATEGORY_GUIDS((short)3, "categoryGuids"),
    HEADERS((short)4, "headers"),
    TUPLES((short)5, "tuples");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // CORRELATION_ID
          return CORRELATION_ID;
        case 3: // CATEGORY_GUIDS
          return CATEGORY_GUIDS;
        case 4: // HEADERS
          return HEADERS;
        case 5: // TUPLES
          return TUPLES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CORRELATION_ID, new org.apache.thrift.meta_data.FieldMetaData("correlationId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CATEGORY_GUIDS, new org.apache.thrift.meta_data.FieldMetaData("categoryGuids", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.HEADERS, new org.apache.thrift.meta_data.FieldMetaData("headers", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.TUPLES, new org.apache.thrift.meta_data.FieldMetaData("tuples", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Tuple.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TupleCollection.class, metaDataMap);
  }

  public TupleCollection() {
  }

  public TupleCollection(
    String id,
    String correlationId,
    List<String> categoryGuids,
    Map<String,String> headers,
    List<Tuple> tuples)
  {
    this();
    this.id = id;
    this.correlationId = correlationId;
    this.categoryGuids = categoryGuids;
    this.headers = headers;
    this.tuples = tuples;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TupleCollection(TupleCollection other) {
    if (other.isSetId()) {
      this.id = other.id;
    }
    if (other.isSetCorrelationId()) {
      this.correlationId = other.correlationId;
    }
    if (other.isSetCategoryGuids()) {
      List<String> __this__categoryGuids = new ArrayList<String>();
      for (String other_element : other.categoryGuids) {
        __this__categoryGuids.add(other_element);
      }
      this.categoryGuids = __this__categoryGuids;
    }
    if (other.isSetHeaders()) {
      Map<String,String> __this__headers = new HashMap<String,String>();
      for (Map.Entry<String, String> other_element : other.headers.entrySet()) {

        String other_element_key = other_element.getKey();
        String other_element_value = other_element.getValue();

        String __this__headers_copy_key = other_element_key;

        String __this__headers_copy_value = other_element_value;

        __this__headers.put(__this__headers_copy_key, __this__headers_copy_value);
      }
      this.headers = __this__headers;
    }
    if (other.isSetTuples()) {
      List<Tuple> __this__tuples = new ArrayList<Tuple>();
      for (Tuple other_element : other.tuples) {
        __this__tuples.add(new Tuple(other_element));
      }
      this.tuples = __this__tuples;
    }
  }

  public TupleCollection deepCopy() {
    return new TupleCollection(this);
  }

  @Override
  public void clear() {
    this.id = null;
    this.correlationId = null;
    this.categoryGuids = null;
    this.headers = null;
    this.tuples = null;
  }

  public String getId() {
    return this.id;
  }

  public TupleCollection setId(String id) {
    this.id = id;
    return this;
  }

  public void unsetId() {
    this.id = null;
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return this.id != null;
  }

  public void setIdIsSet(boolean value) {
    if (!value) {
      this.id = null;
    }
  }

  public String getCorrelationId() {
    return this.correlationId;
  }

  public TupleCollection setCorrelationId(String correlationId) {
    this.correlationId = correlationId;
    return this;
  }

  public void unsetCorrelationId() {
    this.correlationId = null;
  }

  /** Returns true if field correlationId is set (has been assigned a value) and false otherwise */
  public boolean isSetCorrelationId() {
    return this.correlationId != null;
  }

  public void setCorrelationIdIsSet(boolean value) {
    if (!value) {
      this.correlationId = null;
    }
  }

  public int getCategoryGuidsSize() {
    return (this.categoryGuids == null) ? 0 : this.categoryGuids.size();
  }

  public java.util.Iterator<String> getCategoryGuidsIterator() {
    return (this.categoryGuids == null) ? null : this.categoryGuids.iterator();
  }

  public void addToCategoryGuids(String elem) {
    if (this.categoryGuids == null) {
      this.categoryGuids = new ArrayList<String>();
    }
    this.categoryGuids.add(elem);
  }

  public List<String> getCategoryGuids() {
    return this.categoryGuids;
  }

  public TupleCollection setCategoryGuids(List<String> categoryGuids) {
    this.categoryGuids = categoryGuids;
    return this;
  }

  public void unsetCategoryGuids() {
    this.categoryGuids = null;
  }

  /** Returns true if field categoryGuids is set (has been assigned a value) and false otherwise */
  public boolean isSetCategoryGuids() {
    return this.categoryGuids != null;
  }

  public void setCategoryGuidsIsSet(boolean value) {
    if (!value) {
      this.categoryGuids = null;
    }
  }

  public int getHeadersSize() {
    return (this.headers == null) ? 0 : this.headers.size();
  }

  public void putToHeaders(String key, String val) {
    if (this.headers == null) {
      this.headers = new HashMap<String,String>();
    }
    this.headers.put(key, val);
  }

  public Map<String,String> getHeaders() {
    return this.headers;
  }

  public TupleCollection setHeaders(Map<String,String> headers) {
    this.headers = headers;
    return this;
  }

  public void unsetHeaders() {
    this.headers = null;
  }

  /** Returns true if field headers is set (has been assigned a value) and false otherwise */
  public boolean isSetHeaders() {
    return this.headers != null;
  }

  public void setHeadersIsSet(boolean value) {
    if (!value) {
      this.headers = null;
    }
  }

  public int getTuplesSize() {
    return (this.tuples == null) ? 0 : this.tuples.size();
  }

  public java.util.Iterator<Tuple> getTuplesIterator() {
    return (this.tuples == null) ? null : this.tuples.iterator();
  }

  public void addToTuples(Tuple elem) {
    if (this.tuples == null) {
      this.tuples = new ArrayList<Tuple>();
    }
    this.tuples.add(elem);
  }

  public List<Tuple> getTuples() {
    return this.tuples;
  }

  public TupleCollection setTuples(List<Tuple> tuples) {
    this.tuples = tuples;
    return this;
  }

  public void unsetTuples() {
    this.tuples = null;
  }

  /** Returns true if field tuples is set (has been assigned a value) and false otherwise */
  public boolean isSetTuples() {
    return this.tuples != null;
  }

  public void setTuplesIsSet(boolean value) {
    if (!value) {
      this.tuples = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((String)value);
      }
      break;

    case CORRELATION_ID:
      if (value == null) {
        unsetCorrelationId();
      } else {
        setCorrelationId((String)value);
      }
      break;

    case CATEGORY_GUIDS:
      if (value == null) {
        unsetCategoryGuids();
      } else {
        setCategoryGuids((List<String>)value);
      }
      break;

    case HEADERS:
      if (value == null) {
        unsetHeaders();
      } else {
        setHeaders((Map<String,String>)value);
      }
      break;

    case TUPLES:
      if (value == null) {
        unsetTuples();
      } else {
        setTuples((List<Tuple>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case CORRELATION_ID:
      return getCorrelationId();

    case CATEGORY_GUIDS:
      return getCategoryGuids();

    case HEADERS:
      return getHeaders();

    case TUPLES:
      return getTuples();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case CORRELATION_ID:
      return isSetCorrelationId();
    case CATEGORY_GUIDS:
      return isSetCategoryGuids();
    case HEADERS:
      return isSetHeaders();
    case TUPLES:
      return isSetTuples();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TupleCollection)
      return this.equals((TupleCollection)that);
    return false;
  }

  public boolean equals(TupleCollection that) {
    if (that == null)
      return false;

    boolean this_present_id = true && this.isSetId();
    boolean that_present_id = true && that.isSetId();
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (!this.id.equals(that.id))
        return false;
    }

    boolean this_present_correlationId = true && this.isSetCorrelationId();
    boolean that_present_correlationId = true && that.isSetCorrelationId();
    if (this_present_correlationId || that_present_correlationId) {
      if (!(this_present_correlationId && that_present_correlationId))
        return false;
      if (!this.correlationId.equals(that.correlationId))
        return false;
    }

    boolean this_present_categoryGuids = true && this.isSetCategoryGuids();
    boolean that_present_categoryGuids = true && that.isSetCategoryGuids();
    if (this_present_categoryGuids || that_present_categoryGuids) {
      if (!(this_present_categoryGuids && that_present_categoryGuids))
        return false;
      if (!this.categoryGuids.equals(that.categoryGuids))
        return false;
    }

    boolean this_present_headers = true && this.isSetHeaders();
    boolean that_present_headers = true && that.isSetHeaders();
    if (this_present_headers || that_present_headers) {
      if (!(this_present_headers && that_present_headers))
        return false;
      if (!this.headers.equals(that.headers))
        return false;
    }

    boolean this_present_tuples = true && this.isSetTuples();
    boolean that_present_tuples = true && that.isSetTuples();
    if (this_present_tuples || that_present_tuples) {
      if (!(this_present_tuples && that_present_tuples))
        return false;
      if (!this.tuples.equals(that.tuples))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(TupleCollection other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    TupleCollection typedOther = (TupleCollection)other;

    lastComparison = Boolean.valueOf(isSetId()).compareTo(typedOther.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, typedOther.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCorrelationId()).compareTo(typedOther.isSetCorrelationId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCorrelationId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.correlationId, typedOther.correlationId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCategoryGuids()).compareTo(typedOther.isSetCategoryGuids());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCategoryGuids()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.categoryGuids, typedOther.categoryGuids);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetHeaders()).compareTo(typedOther.isSetHeaders());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHeaders()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.headers, typedOther.headers);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTuples()).compareTo(typedOther.isSetTuples());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTuples()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tuples, typedOther.tuples);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TupleCollection(");
    boolean first = true;

    sb.append("id:");
    if (this.id == null) {
      sb.append("null");
    } else {
      sb.append(this.id);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("correlationId:");
    if (this.correlationId == null) {
      sb.append("null");
    } else {
      sb.append(this.correlationId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("categoryGuids:");
    if (this.categoryGuids == null) {
      sb.append("null");
    } else {
      sb.append(this.categoryGuids);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("headers:");
    if (this.headers == null) {
      sb.append("null");
    } else {
      sb.append(this.headers);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("tuples:");
    if (this.tuples == null) {
      sb.append("null");
    } else {
      sb.append(this.tuples);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TupleCollectionStandardSchemeFactory implements SchemeFactory {
    public TupleCollectionStandardScheme getScheme() {
      return new TupleCollectionStandardScheme();
    }
  }

  private static class TupleCollectionStandardScheme extends StandardScheme<TupleCollection> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TupleCollection struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.id = iprot.readString();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CORRELATION_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.correlationId = iprot.readString();
              struct.setCorrelationIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // CATEGORY_GUIDS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list18 = iprot.readListBegin();
                struct.categoryGuids = new ArrayList<String>(_list18.size);
                for (int _i19 = 0; _i19 < _list18.size; ++_i19)
                {
                  String _elem20; // required
                  _elem20 = iprot.readString();
                  struct.categoryGuids.add(_elem20);
                }
                iprot.readListEnd();
              }
              struct.setCategoryGuidsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // HEADERS
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map21 = iprot.readMapBegin();
                struct.headers = new HashMap<String,String>(2*_map21.size);
                for (int _i22 = 0; _i22 < _map21.size; ++_i22)
                {
                  String _key23; // required
                  String _val24; // required
                  _key23 = iprot.readString();
                  _val24 = iprot.readString();
                  struct.headers.put(_key23, _val24);
                }
                iprot.readMapEnd();
              }
              struct.setHeadersIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // TUPLES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list25 = iprot.readListBegin();
                struct.tuples = new ArrayList<Tuple>(_list25.size);
                for (int _i26 = 0; _i26 < _list25.size; ++_i26)
                {
                  Tuple _elem27; // required
                  _elem27 = new Tuple();
                  _elem27.read(iprot);
                  struct.tuples.add(_elem27);
                }
                iprot.readListEnd();
              }
              struct.setTuplesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TupleCollection struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.id != null) {
        oprot.writeFieldBegin(ID_FIELD_DESC);
        oprot.writeString(struct.id);
        oprot.writeFieldEnd();
      }
      if (struct.correlationId != null) {
        oprot.writeFieldBegin(CORRELATION_ID_FIELD_DESC);
        oprot.writeString(struct.correlationId);
        oprot.writeFieldEnd();
      }
      if (struct.categoryGuids != null) {
        oprot.writeFieldBegin(CATEGORY_GUIDS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.categoryGuids.size()));
          for (String _iter28 : struct.categoryGuids)
          {
            oprot.writeString(_iter28);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.headers != null) {
        oprot.writeFieldBegin(HEADERS_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, struct.headers.size()));
          for (Map.Entry<String, String> _iter29 : struct.headers.entrySet())
          {
            oprot.writeString(_iter29.getKey());
            oprot.writeString(_iter29.getValue());
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.tuples != null) {
        oprot.writeFieldBegin(TUPLES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.tuples.size()));
          for (Tuple _iter30 : struct.tuples)
          {
            _iter30.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TupleCollectionTupleSchemeFactory implements SchemeFactory {
    public TupleCollectionTupleScheme getScheme() {
      return new TupleCollectionTupleScheme();
    }
  }

  private static class TupleCollectionTupleScheme extends TupleScheme<TupleCollection> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TupleCollection struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetCorrelationId()) {
        optionals.set(1);
      }
      if (struct.isSetCategoryGuids()) {
        optionals.set(2);
      }
      if (struct.isSetHeaders()) {
        optionals.set(3);
      }
      if (struct.isSetTuples()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetId()) {
        oprot.writeString(struct.id);
      }
      if (struct.isSetCorrelationId()) {
        oprot.writeString(struct.correlationId);
      }
      if (struct.isSetCategoryGuids()) {
        {
          oprot.writeI32(struct.categoryGuids.size());
          for (String _iter31 : struct.categoryGuids)
          {
            oprot.writeString(_iter31);
          }
        }
      }
      if (struct.isSetHeaders()) {
        {
          oprot.writeI32(struct.headers.size());
          for (Map.Entry<String, String> _iter32 : struct.headers.entrySet())
          {
            oprot.writeString(_iter32.getKey());
            oprot.writeString(_iter32.getValue());
          }
        }
      }
      if (struct.isSetTuples()) {
        {
          oprot.writeI32(struct.tuples.size());
          for (Tuple _iter33 : struct.tuples)
          {
            _iter33.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TupleCollection struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        struct.id = iprot.readString();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.correlationId = iprot.readString();
        struct.setCorrelationIdIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list34 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.categoryGuids = new ArrayList<String>(_list34.size);
          for (int _i35 = 0; _i35 < _list34.size; ++_i35)
          {
            String _elem36; // required
            _elem36 = iprot.readString();
            struct.categoryGuids.add(_elem36);
          }
        }
        struct.setCategoryGuidsIsSet(true);
      }
      if (incoming.get(3)) {
        {
          org.apache.thrift.protocol.TMap _map37 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.headers = new HashMap<String,String>(2*_map37.size);
          for (int _i38 = 0; _i38 < _map37.size; ++_i38)
          {
            String _key39; // required
            String _val40; // required
            _key39 = iprot.readString();
            _val40 = iprot.readString();
            struct.headers.put(_key39, _val40);
          }
        }
        struct.setHeadersIsSet(true);
      }
      if (incoming.get(4)) {
        {
          org.apache.thrift.protocol.TList _list41 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.tuples = new ArrayList<Tuple>(_list41.size);
          for (int _i42 = 0; _i42 < _list41.size; ++_i42)
          {
            Tuple _elem43; // required
            _elem43 = new Tuple();
            _elem43.read(iprot);
            struct.tuples.add(_elem43);
          }
        }
        struct.setTuplesIsSet(true);
      }
    }
  }

}

